spring:
  application:
    name: coffee-logger
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: public
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: admin

management:
  server:
    port: 8080
  endpoints:
    web:
      exposure:
        include: health, info
  metrics:
    tags:
      application: ${spring.application.name}
